# Generated by Django 2.2.3 on 2019-07-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190719_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Image_of_Products'),
        ),
    ]
