# Generated by Django 2.2.3 on 2019-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190719_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
