# Generated by Django 2.2.3 on 2019-07-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
